FROM ubuntu:24.04 AS prod_baseos
LABEL maintainer="Steve Barber <steve.barber@nist.gov>"
# Bare minimum of libraries needed to run the above executable
RUN apt update && DEBIAN_FRONTEND="noninteractive" apt upgrade -y && DEBIAN_FRONTEND="noninteractive" apt install -y \
    libboost-chrono-dev \
    libboost-date-time-dev \
    libboost-dev \
    libboost-filesystem-dev \
    libboost-iostreams-dev \
    libboost-program-options-dev \
    libboost-system-dev \
    libboost-thread-dev \
    libcereal-dev \
    libcpprest-dev \
    libstdc++-13-dev \
    libsz2 \
    gcc-14 \
    g++-14
#  && rm -rf /var/lib/apt/lists/* # Don't remove because derivatives may add more pkgs

FROM prod_baseos AS prod_buildbase
LABEL maintainer="Steve Barber <steve.barber@nist.gov>"
ARG home=/ea
ENV HOME=${home}
ENV PKGROOT=${home}
RUN DEBIAN_FRONTEND="noninteractive" apt install -y \
    build-essential \
    ca-certificates \
    cmake \
    curl \
    git \
    libaec-dev \
    nodejs \
    python3-pip \
    pkg-config \
  && rm -rf /var/lib/apt/lists/*
RUN pip3 install --break-system-packages "conan>=2,<3"
RUN mkdir -p /ea/include/ea /ea/lib/ea /ea/bin
ENV PATH $PKGROOT/HDF5/bin:$PATH
WORKDIR $PKGROOT
COPY hdf5-1.14.4-2.tar.gz h5c++.tmpl Makefile ./
RUN make compiler NATIVE_CC=gcc-14 NATIVE_CXX=g++-14

FROM prod_buildbase AS prod_appbuilder
LABEL maintainer="Steve Barber <steve.barber@nist.gov>"
ARG home=/ea
ARG SHIFTY_REPO=https://github.com/gtfierro/shifty.git
ARG SHIFTY_REF=main
ENV HOME=${home}
ENV PKGROOT=${home}
ENV SHIFTY_PREFIX=${home}/shifty
ENV PATH ${home}/.cargo/bin:$PKGROOT/HDF5/bin:$PATH
WORKDIR $PKGROOT
RUN curl -fsS https://sh.rustup.rs | \
    sh -s -- -y --profile minimal --default-toolchain stable
RUN git clone --depth 1 --branch "$SHIFTY_REF" "$SHIFTY_REPO" shifty-src && \
    cmake -S shifty-src/cpp -B shifty-src/build/cpp \
      -DSHIFTY_CPP_BUILD_TESTS=OFF \
      -DCMAKE_INSTALL_PREFIX="$SHIFTY_PREFIX" && \
    CARGO_BUILD_JOBS="$(nproc)" cmake --build shifty-src/build/cpp --target shifty_rust_build --parallel "$(nproc)" && \
    cmake --install shifty-src/build/cpp
COPY conanfile.txt ./
RUN conan profile detect --force && \
    conan remote add dice-group https://conan.dice-research.org/artifactory/api/conan/tentris && \
    CC=gcc-14 CXX=g++-14 conan install . --output-folder=conan --build=missing \
      -c tools.build:jobs="$(nproc)" \
      -s compiler.cppstd=20 \
      -s compiler.version=14 \
      -s compiler.libcxx=libstdc++11 \
      -o '*:shared=False'
COPY libEA ./libEA/
COPY EAd ./EAd/
RUN make build-ead NATIVE_CC=gcc-14 NATIVE_CXX=g++-14 SHIFTY_PREFIX="$SHIFTY_PREFIX"

FROM prod_baseos
LABEL maintainer="Steve Barber <steve.barber@nist.gov>"
ARG home=/ea
ENV HOME=${home}
ENV PKGROOT=${home}
RUN mkdir -p /data /ea/bin && rm -rf /var/lib/apt/lists/*
COPY --from=prod_appbuilder /ea/bin/ /ea/bin/
WORKDIR /data
ENTRYPOINT ["/ea/bin/ead"]
CMD ["-b", "http://0.0.0.0", "-p", "9876"]
VOLUME ["/data"]
EXPOSE 9876/tcp
